version: "3.2"
services:
  web:
    build: .
    container_name: apache
    ports:
      - 8001:80
      - 8002:443
    depends_on:
      - db
    volumes:
      - ./camagru:/var/www/html/
  db:
    container_name: mysqldb
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  php:
    container_name: php
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
volumes:
  db_data: